### ISSUE TITLE
Improve IMU project definition and scope

### ISSUE THREAD

**Issue by arunbatchu** [Shreya-R-Dixit-Memorial-Foundation/EyeDaV2#2]
@AbhiN2001  and @YashDagade  to improve what I have written. 
https://github.com/Shreya-R-Dixit-Memorial-Foundation/EyeDaV2/wiki/IMUModel

**Comment by YashDagade** [comment]
I really like it: what do you think about this though: https://github.com/orgs/Shreya-R-Dixit-Memorial-Foundation/projects/2

and this new wiki page on how to use kanban boards: https://github.com/Shreya-R-Dixit-Memorial-Foundation/EyeDaV2/wiki/KanBan-Boards

Feel free to change them as you wan to
