### ISSUE TITLE
Helping Prankia with GitHub (Good First Issue)

### ISSUE THREAD

**Issue by YashDagade** [Shreya-R-Dixit-Memorial-Foundation/EyeDaV2#3]
Hey Prankia, 

Take this time to resolve this issue and learn more about issues yourself. Issues also also automatically show up on KanBan Boards

Also, usually, this would be done the other way where Pranika would open an issue saying something like I need help understanding GitHub and than the person who helps her will resolve the issue. 

Note we do track how many issues you submit and resolve, and in general it is a good habit to use the issues feature in GitHub. It becomes really helpful when working in big organizations. 

Also for those reading, this is in markdown. Most of the things like announcements or issues are written in markdown. It is kind of like HTML and CSS and kind of like Latex. Its a good fun thing to learn if you want to this summer

**Comment by Pranika7** [comment]
hi
